# Generated by Django 5.1.3 on 2025-12-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_order_last_update_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': ' سفارشات', 'verbose_name_plural': ' سفارشات ثبت شده'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': ' موارد سفارش', 'verbose_name_plural': ' موارد سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': ' آدرس', 'verbose_name_plural': ' آدرس ارسال سفارش'},
        ),
    ]
