# Generated by Django 5.1.3 on 2025-12-12 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': ' مشتری', 'verbose_name_plural': ' مشتری ها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': ' سفارش', 'verbose_name_plural': ' سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصول', 'verbose_name_plural': ' محصولات'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': ' پروفایل', 'verbose_name_plural': ' پروفایل ها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 13, 1, 17, 19, 193511)),
        ),
    ]
